# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
    adapter: postgresql
    encoding: unicode
    pool: 5
    username: <%= ENV['Settings.database.username'] %>
    password: <%= ENV['Settings.database.password'] %>

development:
  <<: *default
  database: weixin_development

test:
  <<: *default
  database: weixin_test

production:
  <<: *default
  database: weixin_production
